server:
  port: 8080

db:
  ip: 34.68.62.196
  schema: clientes_db

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.ip}/${db.schema}?zeroDateTimeBehavior=convertToNull&serverTimezone=GMT-5
    username: root
    password: --854512--
    testWhileIdle: true
    validationQuery: SELECT 1